# Generated by Django 5.2.6 on 2025-12-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_staffprofile_date_joined_staffprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={},
        ),
        migrations.RenameField(
            model_name='memory',
            old_name='user',
            new_name='alumni',
        ),
        migrations.RenameField(
            model_name='memory',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memory_gallery/'),
        ),
    ]
