# Generated by Django 5.2.6 on 2025-12-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_memory_options_rename_user_memory_alumni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='alumni',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memories/'),
        ),
    ]
