# Generated by Django 5.2.6 on 2025-12-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_fund_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='fund',
            name='collected_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fund',
            name='target_amount',
            field=models.IntegerField(),
        ),
    ]
