# Generated by Django 5.2.6 on 2025-12-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_department_alumni_event_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='current_company',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='role',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registered_on',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='alumni',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumni',
            name='name',
            field=models.CharField(default='Alumini Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='passing_year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='register_no',
            field=models.CharField(default='R001', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Student Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='register_no',
            field=models.CharField(default='R001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='department',
            field=models.CharField(default='Computer Science', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='Computer Science', max_length=100),
            preserve_default=False,
        ),
    ]
