# Generated by Django 5.2.6 on 2025-12-17 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_alumni_current_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('register_no', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('admission_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('register_no', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('passing_year', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='name',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='register_no',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='verified_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='register_no',
        ),
        migrations.AddField(
            model_name='alumni',
            name='current_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='alumni_photos/'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.department'),
        ),
    ]
