# Generated by Django 5.2.6 on 2025-12-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_registeredstudent_verifiedalumni_remove_alumni_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
