# Generated by Django 5.2.6 on 2025-12-23 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alumni_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifiedalumni',
            name='department',
        ),
        migrations.RemoveField(
            model_name='verifiedalumni',
            name='email',
        ),
        migrations.RemoveField(
            model_name='verifiedalumni',
            name='name',
        ),
        migrations.RemoveField(
            model_name='verifiedalumni',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='verifiedalumni',
            name='register_no',
        ),
        migrations.AddField(
            model_name='memory',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verifiedalumni',
            name='alumni',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='pages.alumni'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
